name: Run PowerShell Linter

on:
  pull_request:
    branches:
      - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              shell: pwsh
              run: Install-Module -Name PSScriptAnalyzer -Force -AllowClobber

            # Prep for future modules or files
            - name: Run PSScriptAnalyzer
              shell: pwsh
              run: |
                $results = Invoke-ScriptAnalyzer -Path . -Recurse -Severity Error -ExcludeRule PSAvoidUsingConvertToSecureStringWithPlainText -ErrorAction SilentlyContinue
                if ($results.Count -gt 0) {
                    Write-Host "PSScriptAnalyzer found errors:"
                    $results | ForEach-Object { Write-Host $_ }
                    exit 1
                } else {
                    Write-Host "PSScriptAnalyzer found no errors."
                }